#!/usr/bin/fish

function help_build
	echo "usage: "
	echo "build kernel: builds kernel"
	echo "build mkimage/yes/true:	builds kernel and create disk image"
	echo;echo "build help:	displays this text"
	echo "build --help:	do the same thing"
	echo "-ignore-firmware-type: compiles the kernel to try to run even on BIOS"
end

set DEBUG "0"
set IFT "0"

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

#	assuming that current path is in root directory

set KERNEL_VERSION (cat ./kernel/version)

set MKIMAGE 0

if test (count $argv) -ge 1
	for i in $argv
		switch $i
			case "mkimage"
				set MKIMAGE 1
			case "yes"
				set MKIMAGE 1
			case "true"
				set MKIMAGE 1
			case "debug"
			  echo building kernel with debug options
			  set DEBUG "1"
			case "-ignore-firmware-type"
			  set IFT "1"
			  echo ignoring firmware type
		end
	end
end

echo "starting build: CORE $KERNEL_VERSION"

./scripts/kernel/rmimage	#	deletes disk image (if existent)
./scripts/kernel/clean		#	delete files used in previous builds

set compile_args ""

if test $IFT = "1"
  set compile_args $compile_args -ignore-firmware-type
end

if test $DEBUG -eq 1
  ./scripts/kernel/compile debug $compile_args
else
  ./scripts/kernel/compile $compile_args
end

./scripts/kernel/link		#	links kernel objects

if test -e "./bin/kernel/H-OS.bin"
	echo "kernel build: success"
else
	echo "kernel build: failure"
	exit
end

if test $MKIMAGE = 1
  if test $DEBUG = "0"
	  ./scripts/mkimage
	else
	  ./scripts/mkimage debug
	end
end
