#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

rm ./qemu.log

set _log 0
for i in $argv
  if test $i = "log"
    set _log 1
    break
  end
end

#	root dir
qemu-system-x86_64 -m 8192 -drive format=raw,file=./H-OS.hdd -no-reboot -d int -D qemu.log &
# -d int