#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

#	root dir
GTK_THEME=Adwaita-dark qemu-system-x86_64 -m 4096 -machine q35 -drive format=raw,file=./H-OS.hdd
