#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

rm ./qemu.log

#	root dir
qemu-system-x86_64 -m 8192 -machine q35 -drive format=raw,file=./H-OS.hdd -no-reboot -d int &
