#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

set DEBUG "0"
for i in $argv
  switch $i
    case "debug"
      set DEBUG "1"
      echo debug mode
  end
end

if test $DEBUG = "1"
  ./scripts/build mkimage debug
else
  ./scripts/build mkimage
end
./scripts/emulate
