#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

set is_test "0"
if test (count $argv) -ge 1
  if test $argv[1] = "test"
    set is_test "1"
    echo test mode
  end
end

if test $is_test = "1"
  ./scripts/build mkimage test
else
  ./scripts/build mkimage
end
./scripts/emulate
