#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	#	change dir to root
	echo run in project root directory
	exit
end

set include /usr/include

set ccompiler "none"

for i in $PATH
	if test -e "$i/x86_64-elf-g++"
		set ccompiler "$i/x86_64-elf-g++"
		echo using $ccompiler as c++ compiler
		break
	end
end

if test $ccompiler = "none"
	if test (uname -m) = x86_64 -o (uname -m) = amd64
		for i in $PATH
			if test -e "$i/g++"
				set ccompiler "$i/g++"
				echo using $ccompiler as c++ compiler
				break
			end
		end
	else
		#echo error: could not resolve c++ compiler
		echo ERROR: cross compiler for c++ was not found, please install x86_64-elf-gcc package
		exit
	end	
end

#echo compiler $ccompiler

mkdir tmp/kernel -p
	#	create temporary directory for elfs

set acompiler "none"

for i in $PATH
  if test -e "$i/x86_64-elf-as"
    set acompiler "$i/x86_64-elf-as"
    echo using $acompiler as assembly compiler
    break
  end
end

if test $acompiler = "none"
  if test (uname -m) != x86_64 -a (uname -m) != amd64
    echo ERROR: assembly cross compiler was not found, please install x86_64-elf-gcc package
    exit
  end
  for i in $PATH
    if test -e "$i/as"
      set acompiler "$i/as"
      echo using $acompiler as assembly compiler
      break
    end
  end
end

echo;echo;echo;echo
echo compiling asm files ...

for i in (find ./kernel/src/ -name "*.asm")

	set bname (basename $i)
	set bname (string replace ".asm" ".o" -- $bname)

	echo compiling file $i

	#nasm -f elf64 $i -o "./tmp/kernel/$bname"
	$acompiler --64 -o "./tmp/kernel/$bname" $i

end

echo;echo;echo;echo		#	endl
echo compiling c++ kernel ...

gcc -fno-use-cxa-atexit -Wno-missing-field-initializers -ffreestanding -fno-stack-protector -fno-stack-check -fno-lto -fPIE -nostdlib -nostartfiles -Wextra -march=x86-64 -mno-mmx -mno-sse -mno-sse2 -mno-red-zone -m64 -O -c -Wall "./kernel/src/kernel.cpp" -o "./tmp/kernel/kernel.o" -I /mnt/usr/include "-DKERNEL_VERSION=\"$(cat ./kernel/version)\"" -masm=intel
