#!/usr/bin/fish

if test ! (basename (pwd)) = "H-OS"
	echo run in project root directory
	exit
end

mkdir -p ./bin/kernel

echo;echo;echo;echo
echo "linking files together ..."

ld (find ./tmp/kernel -name "*.o") -m elf_x86_64 -nostdlib -static -pie --no-dynamic-linker -z text -z max-page-size=0x1000 -T scripts/kernel/linker.ld -o bin/kernel/H-OS.bin
